language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get install -qqy automake g++-4.8 libcppunit-dev valgrind

script:
  - make
  - make unittest
  - ./unittest
